### PR TITLE
Use rollup-plugin-typescript2 for TS transpilation

### LINKED ISSUE #141: Duplicate JSDoc generated in lib folder
**Describe the bug**
When running `npm run build` the emitted source `.d.ts` files seems to have duplicated JSDocs

**Steps to reproduce the behavior**
Build the project

**Expected behavior**
`.d.ts` files should only have single JSDocs on classes and functions.

**Screenshots**
image

**Info**

| Tool      | Version       |
| --------- | ------------- |
| Poolifier | v2.x.x        |
| Node      | v14.x.x       |
| OS        | linux         |

**Additional context**

Maybe there needs to be a configuration fix in the rollup config?
When running just `npx tsc` everything works normal

### PR DESCRIPTION
**Pull request by jerome-benoit**
Fix duplicate comments in type declaration files.

Close #141

Signed-off-by: Jérôme Benoit <jerome.benoit@sap.com>

## PR Checklist

- [x] Please add a description of your changes.
- [ ] We need your changes to come with unit tests in order to keep this project in quality and easy to maintain.
- [ ] Please add a link to the open issue or task that this pull request will resolve.
- [ ] Add a note to the changelog to indicate the change.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

If yes please indicate it and migration info into the CHANGELOG.md file.

---

### CODE REVIEW

**Comment by pioardi** [comment]
Thanks @jerome-benoit  for your contribution, could you please just explain which benefits we have introducing those changes?
I am sorry I really need a crash course on TS

**Comment by jerome-benoit** [comment]
> Thanks @jerome-benoit for your contribution, could you please just explain which benefits we have introducing those changes?
> I am sorry I really need a crash course on TS

It fixes a bug reported by @Shinigami92

**Comment by pioardi** [comment]
@jerome-benoit  which one please? Do we have an open issue?

Is just to better understand the change :) Thanks in advance

**Comment by jerome-benoit** [comment]
> @jerome-benoit which one please? Do we have an open issue?
> 
> Is just to better understand the change :) Thanks in advance

The link to the issue is in the PR description.

**Comment by pioardi** [comment]
Oh okok, good to go then :)

**Review by pioardi — APPROVED** [review]
Thanks to fix that
Approved

**Comment by jerome-benoit** [comment]
Thanks

**Pull request merged**
