### PR TITLE
Add TypeScript declarations

### PR DESCRIPTION
**Pull request by Shinigami92**

### CODE REVIEW

**Comment by pioardi** [comment]
@Shinigami92  the PR looks great , would you add also an example of usage with typescript into the README file and example folder  ? 

Waiting someone to implement this , great contribution !

**Comment by Shinigami92** [comment]
@pioardi Will do tomorrow at work
Also, thanks for this lib, works like a charm :heart:

**Comment by pioardi** [comment]
@Shinigami92  sounds good , once done I will merge the PR.
I am happy that the lib is working well , for what are you using it if I can ask ? :)

**Comment by Shinigami92** [comment]
@pioardi We are using it for `nestjs`
It's a crawling service and instead of using a Service we now moved all the code that is calling puppeteer into a worker and now the worker is crawling the site
Therefore now we can run multiple POST calls agains one endpoint with only one nestjs instance in parallel
Saved us from 8 seconds per call to 2-8 (dynamic pool) calls in 8 seconds together :sparkles:

**Comment by pioardi** [comment]
Great to know @Shinigami92  , enjoy it :) 
Talk to you tomorrow then :)

**Comment by Shinigami92** [comment]
I don't know how I could add an example to `README.MD`

If you want to add something, can I ask you to do it? 🙂

**Comment by pioardi** [comment]
Is ok @Shinigami92  , I will add a link to your examples .
Going to merge the PR , thanks for your contribution and keep use poolifier 📦

**Comment by Shinigami92** [comment]
@pioardi Type declarations are working + docs + served and working in production ✨ 
Thank you very much for this lib 🙂

**Comment by pioardi** [comment]
Great , I will keep in touch with you if in future will add some new methods and need some ts update 🗡️

**Pull request merged**
