### PR TITLE
Remove usage of module.exports

### PR DESCRIPTION
**Pull request by Shinigami92**
We need to test this change in a real-world environment and maybe add migration guidelines to the changelog

### CODE REVIEW

**Comment by pioardi** [comment]
@Shinigami92  I cannot say thank you enough for all your commitment on this project, you and also jerome.
I would like to connect both of you on gitter to chat a little and know you better.

Anyway coming to your PR, if unit tests worked without changes most likely this is going to work for real word usages

**Comment by Shinigami92** [comment]
I logged into gitter but I'm absolutely not used to it :smile: 
I already use Discord, Slack, Steam, Battle.net, etc. etc.

But yeah, I think I will look into gitter from time to time

**Comment by pioardi** [comment]
For me is ready to go, @jerome-benoit  if you want to take a look, but for me is good and can be merged

**Comment by jerome-benoit** [comment]
> For me is ready to go, @jerome-benoit if you want to take a look, but for me is good and can be merged

I agree.

**Review by jerome-benoit — APPROVED** [review]

**Pull request merged**
