### PR TITLE
Apply all dependencies update at once.

### PR DESCRIPTION
**Pull request by jerome-benoit**
And dedupe.

Signed-off-by: Jérôme Benoit <jerome.benoit@piment-noir.org>

## PR Checklist

- [x] Please add a description of your changes.
- [ ] We need your changes to come with unit tests in order to keep this project in quality and easy to maintain.
- [ ] If your changes contain any new feature please be sure to document it.
- [ ] Please add a link to the open issue or task that this pull request will resolve.
- [ ] Add a note to the changelog to indicate the change.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

If yes please indicate it and migration info into the CHANGELOG.md file.

---

### CODE REVIEW

**Comment by Shinigami92** [comment]
I could approve that, but I'm more interested in finding out why SonarCloud fails and how we can fix that so it is stable again :thinking: 
@pioardi

**Comment by pioardi** [comment]
Hi guys, I regenerated the token that was already correct....I don' t know why this intermittent failure happen the token is correct. I can try to search around the web to check if anyone has a similar issue, in the meanwhile I would not block any PR for that and keep in mind that sometimes with a retry it works.

**Comment by jerome-benoit** [comment]
Can someone please approve and merge?

**Review by pioardi — APPROVED** [review]
Thanks jerome

**Pull request merged**
