### PR TITLE
Publish betas with beta tag

### LINKED ISSUE #197: Poolifier was not tagged as beta in npm
**Describe the bug**
While publishing the newest `2.0.0` of poolifier, it seems that tagging was not.
This is potentially dangerous for our community.

Sadly this bug is NOT fixable anymore because you cannot delete versions from NPM :slightly_frowning_face:  
It can only be fixed when releasing the next `latest` real non-pre-release

But for the future we definitely should not publish beta releases into the latest tag anymore :warning: 

**Steps to reproduce the behavior**

When using e.g. `npm install poolifier` in a project, the current `latest` version of poolifier will be installed.
As can be seen here https://www.npmjs.com/package/poolifier on the versions tab, this is currently `2.0.0-beta.4`

**Expected behavior**

Tagging should have been used to produce tagged versions like in this project

image

**Screenshots**

https://user-images.githubusercontent.com/7195563/108474457-b7888780-728f-11eb-99b7-ebe51167c45c.mp4

**Info**

| Tool      | Version       |
| --------- | ------------- |
| Poolifier | v2.0.0-beta.4 |

**Additional context**

- https://docs.npmjs.com/cli/v6/commands/npm-publish
- https://docs.npmjs.com/about-semantic-versioning
- https://docs.npmjs.com/cli/v6/using-npm/semver#prerelease-tags

### PR DESCRIPTION
**Pull request by Shinigami92**
## PR Checklist

- [x] Please add a description of your changes.
- [ ] We need your changes to come with unit tests in order to keep this project in quality and easy to maintain.
- [x] Please add a link to the open issue or task that this pull request will resolve.
- [ ] Add a note to the changelog to indicate the change.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

If yes please indicate it and migration info into the CHANGELOG.md file.

---

closes #197 

https://github.com/tyankatsu0105/read-package-version-actions

### CODE REVIEW

**Comment by Shinigami92** [comment]
@pioardi @jerome-benoit I have literally NO idea if this is working :warning:  
Does someone of you have better knowledge of GH actions?

**Comment by pioardi** [comment]
Thanks @Shinigami92  to work on that, I will look into this as soon as I can

**Comment by jerome-benoit** [comment]
> @pioardi @jerome-benoit I have literally NO idea if this is working ⚠️
> Does someone of you have better knowledge of GH actions?

That looks correct. That can be tested during the beta release cycle.

**Comment by Shinigami92** [comment]
> That looks correct. That can be tested during the beta release cycle.

Yeah that is also what I think
We could also try adding a test workflow and watch the behavior
Or just go yolo :laughing:

**Comment by Shinigami92** [comment]
It really seems to work :tada: 

I created a test repo and there you have

1. A beta candidate workflow run:
https://github.com/Shinigami92/test-gh-actions-version-extraction/runs/1942444027?check_suite_focus=true#step:6:1

2. A release candidate workflow run:
https://github.com/Shinigami92/test-gh-actions-version-extraction/runs/1942448600?check_suite_focus=true#step:5:1

**Review by jerome-benoit — APPROVED** [review]

**Pull request merged**
