### PR TITLE
Issue 160 ci unit test

### PR DESCRIPTION
**Pull request by pioardi**
## PR Checklist

- [x] Please add a description of your changes.
- [x] We need your changes to come with unit tests in order to keep this project in quality and easy to maintain.
- [x] Please add a link to the open issue or task that this pull request will resolve.
- [ ] Add a note to the changelog to indicate the change.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

If yes please indicate it and migration info into the CHANGELOG.md file.

---

I fixed the issue number 160, I also added the parallel option to our tests so now each test file will run in parallel from others

### CODE REVIEW

**Comment by pioardi** [comment]
I see now another error on the tests when running the CI, it does not happen locally

**Comment by pioardi** [comment]
The new error is EPIPE, it is happening now rarely compared to the previous but it is more difficult to fix since that we do not have a way to know if the clear interval already happened, we can try to use process.nextTick to fix also the new error

**Review by jerome-benoit — APPROVED** [review]
Bug definitely fixed or not, the code consolidation make sense.

**Comment by pioardi** [comment]
> Bug definitely fixed or not, the code consolidation make sense.

Yes also now we send the kill to the worker also for fixed threads that is a good thing.
I will merge this for now and see later how to fix the EPIPE ( is more difficult )

**Pull request merged**
