### PR TITLE
Consolidate sleep implementation in tests

### PR DESCRIPTION
**Pull request by jerome-benoit**
And move workers code to the right place.

Signed-off-by: Jérôme Benoit <jerome.benoit@sap.com>

## PR Checklist

- [x] Please add a description of your changes.
- [ ] We need your changes to come with unit tests in order to keep this project in quality and easy to maintain.
- [ ] Please add a link to the open issue or task that this pull request will resolve.
- [ ] Add a note to the changelog to indicate the change.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

If yes please indicate it and migration info into the CHANGELOG.md file.

---

### CODE REVIEW

**Comment by pioardi** [comment]
@jerome-benoit  I think I did the same stuff into the other PR ( sad ), please take a look there

**Comment by pioardi** [comment]
If you agree I would close this PR @jerome-benoit , kindly let me know :)

**Comment by jerome-benoit** [comment]
> If you agree I would close this PR @jerome-benoit , kindly let me know :)

That's not the same PR.

**Comment by jerome-benoit** [comment]
> > If you agree I would close this PR @jerome-benoit , kindly let me know :)
> 
> That's not the same PR but yes.

**Comment by pioardi** [comment]
I am sorry we got this small overlap

**Pull request closed without merging**
