### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by jerome-benoit**
Signed-off-by: Jérôme Benoit <jerome.benoit@sap.com>

## PR Checklist

- [x] Please add a description of your changes.
- [ ] We need your changes to come with unit tests in order to keep this project in quality and easy to maintain.
- [ ] If your changes contain any new feature please be sure to document it.
- [ ] Please add a link to the open issue or task that this pull request will resolve.
- [ ] Add a note to the changelog to indicate the change.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

If yes please indicate it and migration info into the CHANGELOG.md file.

---

### CODE REVIEW

**Comment by Shinigami92** [comment]
I will not approve these bundled updates as long as @pioardi havn't found a fix for `Sonar Code Analysis`

**Comment by jerome-benoit** [comment]
> I will not approve these bundled updates as long as @pioardi havn't found a fix for `Sonar Code Analysis`

Since it only happens on the dependabot PRs, it might also be related to its setup.

**Comment by Shinigami92** [comment]
> > I will not approve these bundled updates as long as @pioardi havn't found a fix for `Sonar Code Analysis`
> 
> Since it only happens on the dependabot PRs, it might also be related to its setup.

Yeah, something like permission tokens or so 🤔

**Review by pioardi — APPROVED** [review]
@jerome-benoit  thanks for all your time on this.

**Comment by Shinigami92** [comment]
https://github.com/pioardi/poolifier/pull/323/checks?check_run_id=2435105644#step:8:194

This line tells that there is an issue with the permission to SonarQube

**Pull request merged**
