### PR TITLE
Create an abstract class for pool implementation 

### PR DESCRIPTION
**Pull request by jerome-benoit**
To ease the integration of futur pool implementation.

Future pool implementation will permit to refine the API defined for pool implementation. 

Signed-off-by: Jérôme Benoit <jerome.benoit@sap.com>

### CODE REVIEW

**Comment by pioardi** [comment]
I will try to look into this PR tomorrow, for now I can only say that task on node 14.x version is failing

**Comment by jerome-benoit** [comment]
> I will try to look into this PR tomorrow, for now I can only say that task on node 14.x version is failing

Probably an issue with GitHub CI infrastructure ...

**Comment by Shinigami92** [comment]
@jerome-benoit Would it be possible for you to wait a little bit until I at least start working on #66. Hopefully we can see better what we can extract of logic and types

**Comment by jerome-benoit** [comment]
> @jerome-benoit Would it be possible for you to wait a little bit until I at least start working on #66. Hopefully we can see better what we can extract of logic and types

It can wait for the current PRs to be merged, I will update that PR. 
But it's just the global code structure to follow for pool implementation. So merging it before any work on new pool implementation is a must. The API here is not a step in stone, it will change but the overall structure shall be followed. And the API changes are expected to happen during new pool implementation coding.

**Comment by Shinigami92** [comment]
Yeah, I understand your point, but maybe there are differences between a cluster pool and a worker pool
So let's find these diffs first before defining the abstract pool and then trying to figure out what needs to be moved out of the abstraction

IMO it's better to abstract things afterwards instead of forcing an abstraction
I hope you understand what I mean ^^

**Comment by jerome-benoit** [comment]
> Yeah, I understand your point, but maybe there are differences between a cluster pool and a worker pool
> So let's find these diffs first before defining the abstract pool and then trying to figure out what needs to be moved out of the abstraction
> 
> IMO it's better to abstract things afterwards instead of forcing an abstraction
> I hope you understand what I mean ^^
> 


The other way around also works.
I do not care about the methodology used to reach the same design pattern implementation for pool.

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by Shinigami92** [comment]
> The other way around also works. I do not care about the methodology used to reach the same design pattern implementation for pool.

You should observe my #92 PR, and see the diff between `cluster/fixed` and `thread/fixed`
Also between `cluster-worker` and `thread-worker`
Hope you can then see that we need e.g. different imports from `node` and use different strategies here and there
Yes we can create an interface to force the "API", but we could also try to create an `abstract class` holding the common logic

**Comment by jerome-benoit** [comment]
> > The other way around also works. I do not care about the methodology used to reach the same design pattern implementation for pool.
> 
> You should observe my #92 PR, and see the diff between `cluster/fixed` and `thread/fixed`
> Also between `cluster-worker` and `thread-worker`
> Hope you can then see that we need e.g. different imports from `node` and use different strategies here and there
> Yes we can create an interface to force the "API", but we could also try to create an `abstract class` holding the common logic

The pool abstract class here was meant for that ;)

I close that PR and wait for the dust to settle.

**Pull request closed without merging**
