### PR TITLE
Use the current node.js LTS version for publication.

### PR DESCRIPTION
**Pull request by jerome-benoit**
Keep node.js previous LTS in CI only

Signed-off-by: Jérôme Benoit <jerome.benoit@sap.com>

## PR Checklist

- [x] Please add a description of your changes.
- [ ] We need your changes to come with unit tests in order to keep this project in quality and easy to maintain.
- [ ] Please add a link to the open issue or task that this pull request will resolve.
- [ ] Add a note to the changelog to indicate the change.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

If yes please indicate it and migration info into the CHANGELOG.md file.

---

### CODE REVIEW

**Review by pioardi — APPROVED** [review]

**Comment by Shinigami92** [comment]
What's the benefit of this PR?

**Comment by jerome-benoit** [comment]
> What's the benefit of this PR?
> 
> 

Use the active version of node.js LTS during the release process instead of the maintenance one.
Align node.js version main target in CI actions.

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by Shinigami92** [comment]
node itself isn't used at all in the CI here
And both, 12 and 14, currently use the same **npm** **version** :shrug: 

image

So IMO there is zero benefit in this PR :confused:

**Comment by jerome-benoit** [comment]
> node itself isn't used at all in the CI here
> 

It’s used in the validation job before pushing the release.

> And both, 12 and 14, currently use the same npm version 🤷
> 
>  <https://user-images.githubusercontent.com/7195563/108844870-f2b2ef80-75dc-11eb-8a54-098ccb8adf0f.png>

There’s only benefits to align the main node.js version targeted everywhere.

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by Shinigami92** [comment]
You can merge it

**Pull request merged**
