### PR TITLE
Cleanups on bechmarking and strategies code:

### PR DESCRIPTION
**Pull request by jerome-benoit**
+ Factor out common code
+ Renaming
+ Add benchmarking on strategies
+ Add microtime to improve benchmark time resolution
+ Small optimisation on less used strategy for fixed pool: constify dynamic var before using it a loop.

Signed-off-by: Jérôme Benoit <jerome.benoit@sap.com>

## PR Checklist

- [x] Please add a description of your changes.
- [ ] We need your changes to come with unit tests in order to keep this project in quality and easy to maintain.
- [ ] Please add a link to the open issue or task that this pull request will resolve.
- [ ] Add a note to the changelog to indicate the change.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

If yes please indicate it and migration info into the CHANGELOG.md file.

---

### CODE REVIEW

**Review by pioardi — APPROVED** [review]
Looks good

**Comment by jerome-benoit** [comment]
Can some please explain me why coverage on new code is 96.2%? 
The report on the culprit file shows everything in green ...

**Comment by pioardi** [comment]
> Can some please explain me why coverage on new code is 96.2%?
> The report on the culprit file shows everything in green ...

Coverage that is showed here is the coverage on the new code

**Comment by jerome-benoit** [comment]
> > Can some please explain me why coverage on new code is 96.2%?
> > The report on the culprit file shows everything in green ...
> 
> Coverage that is showed here is the coverage on the new code

How can I make it reach 100% then if the sonar report show that's all is green in the file with  96.2% coverage?

**Comment by pioardi** [comment]
> > Can some please explain me why coverage on new code is 96.2%?
> > The report on the culprit file shows everything in green ...
> 
> Coverage that is showed here is the coverage on the new code

Looking on sonar all the code seems covered so I don't know why in this case it detects around 96%

**Review by Shinigami92 — APPROVED** [review]

**Pull request merged**
