### PR TITLE
Benchmark: Ensure choice algos does not init with off-by-one

### PR DESCRIPTION
**Pull request by jerome-benoit**
Signed-off-by: Jérôme Benoit <jerome.benoit@sap.com>

## PR Checklist

- [x] Please add a description of your changes.
- [ ] We need your changes to come with unit tests in order to keep this project in quality and easy to maintain.
- [ ] Please add a link to the open issue or task that this pull request will resolve.
- [ ] Add a note to the changelog to indicate the change.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

If yes please indicate it and migration info into the CHANGELOG.md file.

---

### CODE REVIEW

**Review by pioardi — APPROVED** [review]
Approved

**Comment by Shinigami92** [comment]
@jerome-benoit Could you provide a screenshot of your local machine results? :slightly_smiling_face:

**Review by Shinigami92 — CHANGES_REQUESTED** [review]
IMO you should not alter current functions but just add further functions
So we will have maybe 4+ different functions that compare each other
That way, the benchmark result becomes more and more improved

**Comment by Shinigami92** [comment]
So I think we should use
```ts
const Benchmark = require('benchmark')

const suite = new Benchmark.Suite()

const LIST_FORMATTER = new Intl.ListFormat('en-US', {
  style: 'long',
  type: 'conjunction'
})

const workers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

let nextWorkerIndex = 0

function chooseWorkerTernary () {
  nextWorkerIndex =
    workers.length - 1 === nextWorkerIndex ? 0 : nextWorkerIndex + 1
  return workers[nextWorkerIndex]
}

function chooseWorkerTernaryWithNegation () {
  nextWorkerIndex =
    !nextWorkerIndex || workers.length - 1 === nextWorkerIndex
      ? 0
      : nextWorkerIndex + 1
  return workers[nextWorkerIndex]
}

function chooseWorkerTernaryWithPreChoosing () {
  const chosenWorker = workers[nextWorkerIndex]
  nextWorkerIndex =
    workers.length - 1 === nextWorkerIndex ? 0 : nextWorkerIndex + 1
  return chosenWorker
}

function chooseWorkerIncrementModulo () {
  const chosenWorker = workers[nextWorkerIndex]
  nextWorkerIndex++
  nextWorkerIndex %= workers.length
  return chosenWorker
}

suite
  .add('Ternary', function () {
    nextWorkerIndex = 0
    chooseWorkerTernary()
  })
  .add('Ternary with negation', function () {
    nextWorkerIndex = 0
    chooseWorkerTernaryWithNegation()
  })
  .add('Ternary with PreChoosing', function () {
    nextWorkerIndex = 0
    chooseWorkerTernaryWithPreChoosing()
  })
  .add('Increment+Modulo', function () {
    nextWorkerIndex = 0
    chooseWorkerIncrementModulo()
  })
  .on('cycle', function (event) {
    console.log(event.target.toString())
  })
  .on('complete', function () {
    console.log(
      'Fastest is ' + LIST_FORMATTER.format(this.filter('fastest').map('name'))
    )
    // eslint-disable-next-line no-process-exit
    process.exit()
  })
  .run()
```

If you allow me, I can checkin the changes

**Comment by Shinigami92** [comment]
My current result is
image

**Review by Shinigami92 — APPROVED** [review]

**Pull request merged**
