### PR TITLE
Fix nodemon support after TS rewrite. 

### PR DESCRIPTION
**Pull request by jerome-benoit**
And dedupe package-lock.json.

### CODE REVIEW

**Comment by Shinigami92** [comment]
Why is your `package-lock.json` so much different than what I emit as an result of using `rm -Rf node_moudles package-lock.json && npm install`

I'm using `nvm use 14`
`Now using node v14.15.4 (npm v6.14.10)`

**Comment by jerome-benoit** [comment]
> Why is your `package-lock.json` so much different than what I emit as an result of using `rm -Rf node_moudles package-lock.json && npm install`
> 
> I'm using `nvm use 14`
> `Now using node v14.15.4 (npm v6.14.10)`

The one here have no duplicates. npm must been told to do so: `npm dedupe`

**Comment by Shinigami92** [comment]
I'm not used to `npm` but `yarn`
Why isn't it part of the default process by using `npm install`, so why do I need to extra call it afterwards?
Is there any risk involved?
Also, is it configurable like e.g. in a `.npmrc`? So I don't miss to use it?

**Comment by jerome-benoit** [comment]
> I'm not used to `npm` but `yarn`
> Why isn't it part of the default process by using `npm install`, so why do I need to extra call it afterwards?

Dunno. That's just the way npm works. 

> Is there any risk involved?

None. 

> Also, is it configurable like e.g. in a `.npmrc`? So I don't miss to use it?

I do not think you can force npm to dedupe at install via a tunable. 
But it's a detail, having file with duplicates make just the install phase a very small time longer.

**Comment by Shinigami92** [comment]
Just in case, I want to question the title if this PR...
`nodemon` is currently not even a part of the `package.json` in `master`
https://github.com/pioardi/poolifier/blob/master/package.json

Maybe you should open a PR based directly on `master` instead of `issue-62-rewrite-to-typescript`

**Comment by pioardi** [comment]
Do we really need nodemon for this project? I mean this is not a webapp that start as runtime.
Maybe we can just remove nodemon at all ? What are your thoughts on that?

It is probably here for my bad

**Comment by jerome-benoit** [comment]
> Just in case, I want to question the title if this PR...
> `nodemon` is currently not even a part of the `package.json` in `master`
> [https://github.com/pioardi/poolifier/blob/master/package.json](https://github.com/pioardi/poolifier/blob/master/package.json?rgh-link-date=2021-02-07T21%3A26%3A43Z)

It's here: 

  ` "demontest": "nodemon --exec \"npm test\"",`

> Maybe you should open a PR based directly on `master` instead of `issue-62-rewrite-to-typescript`

The added nodemon configuration file was specific to the TS rewrite.

**Comment by jerome-benoit** [comment]
> Do we really need nodemon for this project? I mean this is not a webapp that start as runtime.
> Maybe we can just remove nodemon at all ? What are your thoughts on that?

Probably not. I've just make it work again after the TS rewrite, just in case. @Shinigami92 can also just delete the script in the TS rewrite PR.

**Comment by Shinigami92** [comment]
> The added nodemon configuration file was specific to the TS rewrite.

As pointed out here: https://github.com/pioardi/poolifier/pull/78#issuecomment-775039665  
-> NO it wasn't!

I have the same opinion as pioardi and we should remove it just from the master branch

https://github.com/pioardi/poolifier/blob/81b32bff421a11b3ee2dfd18088717df80659908/package.json#L11

**Comment by jerome-benoit** [comment]
> > The added nodemon configuration file was specific to the TS rewrite.
> 
> As pointed out here: [#78 (comment)](https://github.com/pioardi/poolifier/pull/78#issuecomment-775039665)
> -> NO it wasn't!

Trust me, the file added in that PR was to make the script using nodemon works again after the TS rewrite ;) (restart loop: build change lib that trigger nodemon call that build that ...) 

> 
> I have the same opinion as pioardi and we should remove it just from the master branch
> 

Just delete the script in your TS rewrite PR, the script was renamed here, so it will generate useless conflicts in the TS rewrite PR if it's deleted in master first.

**Comment by Shinigami92** [comment]
> Just delete the script in your TS rewrite PR, [...]

So we can close this PR (`Fix nodemon support after TS rewrite`)?
Because it doesn't fulfill it's purpose anymore

**Comment by jerome-benoit** [comment]
> > Just delete the script in your TS rewrite PR, [...]
> 
> So we can close this PR (`Fix nodemon support after TS rewrite`)?
> Because it doesn't fulfill it's purpose anymore

Sure, I'm pretty you will love to close it yourself ;)

**Comment by Shinigami92** [comment]
> Sure, I'm pretty sure you will love to close it yourself ;)

GitHub automation will do this

**Pull request closed without merging**
